name: Ideal Barnacle Test

on:
  push:
    branches:
      - main

jobs:
  test:
    name: "Test job"
    runs-on: ubuntu-latest
    steps:
      - uses: TomasDiez99/ideal-barnacle@main
      - run: echo "Fin workflow"