name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  setup:
    name: "Setup python tests with pylint and flake8"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: TomasDiez99/friendly-carnival
          ref: main
      - run: |
          pip freeze > requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: |
          flake8 main.py
      - run: |
          pylint main.py

  test:
    name: "Unit test"
    needs: [setup]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jmoyano/ubiquitous-bassoon
          ref: main
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - run: |
          pip install -r requirements.txt
      - run: |
          python -m unittest --verbose --failfast
  build:
    name: "Upload main script"
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: TomasDiez99/friendly-carnival
          ref: main
      - name: Install dependencies
        run: pip install -r /path/to/requirements.txt
      - run: |
          python main.py
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./build/
  deploy:
    name: "Deploy and install"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build
      - run: |
          curl -v --stderr deploy.log -w "${http_code}\n" -F password=<${{ secrets.PASSWORD_EATI2023 }}> -F file=@build -F user=<${{ secrets.USER_EATI2023 }}>
      - run: |
          echo "Fin deploy"